name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Download submodules
      shell: bash
      run: |
          git submodule update --init --recursive 
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt
        git clone https://github.com/tschijnmo/DummyRDD.git
        cd DummyRDD; python3 setup.py install; cd ..
    - name: Install
      run: |
        python3 setup.py install
    - name: Test with pytest
      env:
        DUMMY_SPARK: 1
      run: |
        cd tests 
        pip install coveralls
        coverage run --source=drudge -m pytest -sv
        pip install pytest
        pytest
        cd ..
        
